# Generated by Django 5.0.1 on 2024-01-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_caruselmodel_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caruselmodel',
            old_name='imgage',
            new_name='image',
        ),
    ]
