# Generated by Django 5.0.1 on 2024-01-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_blogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='phrase_creater_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
