# Generated by Django 5.0.1 on 2024-02-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
