# Generated by Django 5.0.1 on 2024-02-14 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_messagemodel_email_messagemodel_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.postmodel'),
        ),
    ]
