# Generated by Django 5.0.1 on 2024-02-01 17:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_wiselistmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WiseListModel',
            new_name='WishListModel',
        ),
    ]
