# Generated by Django 5.0.1 on 2024-02-01 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_wishlistmodel_created_at_wishlistmodel_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistmodel',
            unique_together={('user', 'product')},
        ),
    ]
