# Generated by Django 5.0.1 on 2024-02-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wishlistmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
