# Generated by Django 5.0.1 on 2024-02-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_wishlistmodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image_1', models.ImageField(upload_to='blog_detail')),
                ('image_2', models.ImageField(upload_to='blog_detail')),
                ('image_3', models.ImageField(upload_to='blog_detail')),
                ('image_4', models.ImageField(upload_to='blog_detail')),
            ],
            options={
                'verbose_name': 'PostGallery',
                'verbose_name_plural': 'PostGalleries',
            },
        ),
    ]
