# Generated by Django 5.0.1 on 2024-02-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_productmodel_gallery_productmodel_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postgallerymodel',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='postgallerymodel',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='postgallerymodel',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='postgallerymodel',
            name='image_4',
        ),
    ]
