# Generated by Django 5.0.1 on 2024-02-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_image_postgallerymodel_image_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postgallerymodel',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='postgallerymodel',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='postgallerymodel',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='postgallerymodel',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='gallery',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='gallery',
            field=models.ManyToManyField(blank=True, null=True, to='products.postgallerymodel'),
        ),
    ]
