# Generated by Django 5.0.1 on 2024-03-05 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_image_1_postgallerymodel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='gallery',
        ),
        migrations.CreateModel(
            name='ProductImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/neasted_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productmodel')),
            ],
            options={
                'verbose_name': 'product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.DeleteModel(
            name='PostGalleryModel',
        ),
    ]
