# Generated by Django 5.0.1 on 2024-03-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_cupinmodel_created_at_cupinmodel_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CupinModel',
            new_name='CupounModel',
        ),
    ]
